# Generated by Django 5.1.6 on 2025-02-21 02:04

import django.db.models.deletion
import tinymce.models
import video_encoding.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='theorie',
            new_name='explication',
        ),
        migrations.RemoveField(
            model_name='theorie',
            name='video',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.CharField(default='Anonyme', max_length=255),
        ),
        migrations.AddField(
            model_name='theorie',
            name='contenu',
            field=tinymce.models.HTMLField(default='Contenu par défaut'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(default='Aucun contenu'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', video_encoding.fields.VideoField(blank=True, null=True, upload_to='video/')),
                ('explication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='enquetes.theorie')),
            ],
        ),
    ]
