# Generated by Django 5.1.6 on 2025-03-05 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquetes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_enquetes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='theorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.theorie'),
        ),
        migrations.AddField(
            model_name='video',
            name='explication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='enquetes.theorie'),
        ),
    ]
