# Generated by Django 5.1.6 on 2025-03-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='explication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='enquetes.theorie'),
        ),
    ]
