# Generated by Django 5.1.6 on 2025-02-20 22:31

import django.db.models.deletion
import tinymce.models
import video_encoding.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', tinymce.models.HTMLField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='statu.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('explication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='debunk.explication')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', video_encoding.fields.VideoField(blank=True, null=True, upload_to='video/')),
                ('explication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='debunk.explication')),
            ],
        ),
    ]
